name: Weekly Automated Blog Post

on:
  schedule:
    - cron: '30 20 * * TUE'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install mkdocs mkdocs-material openai PyYAML

      - name: Generate Blog Post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_post.py

      - name: Set Remote with PAT
        env:
          GIT_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GIT_TOKEN}@github.com/MateuszNowakowski2024/ds_ai_portfolio.git
          git fetch origin main
          git checkout -B main origin/main
          git pull --rebase origin main

      - name: Commit and push changes
        run: |
          git config --global user.name 'Github-Actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Automated blog post"
          git push -f origin main 

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site
