name: Weekly Automated Blog Post

on:
  schedule:
    - cron: '30 20 * * MON' # 8:30 PM every Monday
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install mkdocs mkdocs-material openai PyYAML

      - name: Set Remote with PAT
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }} 
        run: |
          git remote set-url origin https://x-access-token:${PERSONAL_TOKEN}@github.com/MateuszNowakowski2024/ds_ai_portfolio.git
          git fetch origin main
          git checkout -B main origin/main

      - name: Generate and Commit Changes
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
        run: |
          # Generate blog post
          python generate_post.py
          
          # Configure git user
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Commit changes
          git add .
          git commit -m "Automated blog post - $(date +'%Y-%m-%d')"

      - name: Ensure Up-to-Date Branch
        run: |
          # Pull changes from remote to ensure no conflicts before pushing
          git pull --rebase origin main

      - name: Push changes to main
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }} # noqa
        run: |
          git push origin main

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # noqa
          publish_dir: ./site

