name: Weekly Automated Blog Post

on:
  schedule:
    - cron: '30 20 * * TUE'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_and_deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install mkdocs mkdocs-material openai PyYAML
      - name: Check out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched
          ref: main

      - name: Generate and Commit Changes
        run: |
          # Generate blog post
          python generate_post.py
        
      - name: Check out Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched
          ref: main
        
      - name: Set Remote with PAT
        env:
          GIT_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
            git remote set-url origin https://x-access-token:${GIT_TOKEN}@github.com/MateuszNowakowski2024/ds_ai_portfolio.git
            git fetch origin main
            git checkout -B main origin/main
      
      - name: Commit and Push Changes
        env:
          GIT_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Automated blog post - $(date +'%Y-%m-%d')"
          git push 
        

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site
